=== ngadzheva/XML-labs/week 3/exercises/ex 2/bank.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="bank" type="bankInfo"/>

    <xs:complexType name="bankInfo" mixed="true">
        <xs:sequence>
            <xs:element name="accounts" minOccurs="1">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="saving_accounts" type="savingAccounts"/>
                        <xs:element name="checking_accounts" type="checkingAccounts"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            
            <xs:element name="customers" type="customers" minOccurs="1"/>
            
            <xs:element name="customer_accounts" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="customer_account" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="c_id" type="xs:IDREF" use="required"/>
                                <xs:attribute name="ac_id" type="xs:IDREF" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="customers">
        <xs:sequence>
            <xs:element name="customer" type="customerInfo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="customerInfo">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
        </xs:sequence>

        <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>

    <xs:complexType name="savingAccounts">
        <xs:sequence>
            <xs:element name="saving_account" type="savingAccountInfo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="balance"> 
   	   <xs:simpleType> 
   	   	   <xs:restriction base="xs:decimal"> 
   	   	   	   <xs:minInclusive value="-5000"/> 
   	   	   </xs:restriction> 
   	   </xs:simpleType> 
   </xs:element> 

    <xs:complexType name="savingAccountInfo">
        <xs:sequence>
            <xs:element ref="balance"/>
        </xs:sequence>

        <xs:attribute name="id" use="required" type="xs:ID"/>
        <xs:attribute name="interest" type="xs:decimal"/>
    </xs:complexType>

    <xs:complexType name="checkingAccounts">
        <xs:sequence>
            <xs:element name="checking_account" type="checkingAccountInfo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="checkingAccountInfo">
        <xs:sequence>
            <xs:element ref="balance"/>
        </xs:sequence>

        <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
</xs:schema>

=== ngadzheva/XML-labs/week 3/exercises/ex 2/bank.xml
<?xml version="1.0" encoding="UTF-8"?> 
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bank.xsd"> 
   <accounts> 
   	   <saving_accounts> 
   	   	   <saving_account id="a1" interest="0.03"> 
   	   	   	   <balance>2500</balance> 
   	   	   </saving_account> 
   	   	   <saving_account id="a2" interest="0.03"> 
   	   	   	   <balance>15075</balance> 
   	   	   </saving_account> 
   	   </saving_accounts> 
   	   <checking_accounts> 
   	   	   <checking_account id="a3"> 
   	   	   	   <balance>4025</balance> 
   	   	   </checking_account> 
   	   	   <checking_account id="a4"> 
   	   	   	   <balance>-125</balance> 
   	   	   </checking_account> 
   	   	   <checking_account id="a5"> 
   	   	   	   <balance>325</balance> 
   	   	   </checking_account> 
   	   </checking_accounts> 
   </accounts> 
   <customers> 
   	   <customer id="c1"> 
   	   	   <name>Ben Richerdson</name> 
   	   	   <address>Park Drive 2</address> 
   	   </customer> 
   	   <customer id="c2"> 
   	   	   <name>Marc Wretcher</name> 
   	   	   <address>Mill Drive 75</address> 
   	   </customer> 
   	   <customer id="c3"> 
   	   	   <name>Angel Steady</name> 
   	   	   <address>Lake Sight 15</address> 
   	   </customer> 
   </customers> 
   <customer_accounts> 
   	   <customer_account c_id="c1" ac_id="a2"/> 
   	   <customer_account c_id="c1" ac_id="a3"/> 
   	   <customer_account c_id="c2" ac_id="a4"/> 
   	   <customer_account c_id="c3" ac_id="a1"/> 
   	   <customer_account c_id="c3" ac_id="a5"/> 
   </customer_accounts> 
</bank>
