=== ngadzheva/XML-labs/week 2/exercises/task 3/courseCatalog.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!ELEMENT Course_Catalog (Department+)>
<!ELEMENT Department (Title, Chair, Course+)>
<!ATTLIST Department Code (CS | EE | LING) #REQUIRED> 
<!ELEMENT Title (#PCDATA)> 
<!ELEMENT Chair (Professor)>
<!ELEMENT Professor (First_Name, Middle_Initial?, Last_Name)> 
<!ELEMENT First_Name (#PCDATA)> 
<!ELEMENT Middle_Initial (#PCDATA)>
<!ELEMENT Last_Name (#PCDATA)>  
<!ELEMENT Course (Title, Description?, Instructors, Prerequisites?)>  
<!ATTLIST Course 
            Number (CS106A | CS106B | CS107 | CS109 | CS124 | CS143 | CS145 | CS221 | CS228 | CS229 | EE108A | EE108B | LING180) #REQUIRED 
            Enrollment (1070 | 110 | 130 | 180 | 280 | 320 | 500 | 60 | 620 | 90) #IMPLIED > 
<!ELEMENT Description (#PCDATA)> 
<!ELEMENT Instructors ((Lecturer, Professor*) | (Professor+, Lecturer?))> 
<!ELEMENT Lecturer (First_Name, Middle_Initial?, Last_Name)> 
<!ELEMENT Prerequisites (Prereq+)>  
<!ELEMENT Prereq (#PCDATA)>

=== ngadzheva/XML-labs/week 2/exercises/task 3/courseCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Course_Catalog SYSTEM "courseCatalog.dtd">

<Course_Catalog> 
    <Department Code="CS"> 
        <Title>Computer Science</Title> 
        <Chair> 
            <Professor> 
                <First_Name>Jennifer</First_Name> 
                <Last_Name>Widom</Last_Name> 
            </Professor> 
        </Chair> 

        <Course Number="CS106A" Enrollment="1070"> 
            <Title>Programming Methodology</Title> 
            <Description>Introduction to the engineering of computer applications emphasizing modern software engineering principles.</Description> 
            <Instructors> 
                <Lecturer> 
                    <First_Name>Jerry</First_Name> 
                    <Middle_Initial>R.</Middle_Initial> 
                    <Last_Name>Cain</Last_Name> 
                </Lecturer>
                <Professor> 
                    <First_Name>Eric</First_Name> 
                    <Last_Name>Roberts</Last_Name> 
                </Professor> 
            </Instructors> 
        </Course> 
    </Department> 
</Course_Catalog>
